CREATE TABLE  "ANGAJAT" 
   (	"CNP" NUMBER(13,0) NOT NULL ENABLE, 
	"NUME" VARCHAR2(100) NOT NULL ENABLE, 
	"PRENUME" VARCHAR2(100) NOT NULL ENABLE, 
	"DATA_NASTERE" DATE NOT NULL ENABLE, 
	"ADRESA" VARCHAR2(100) NOT NULL ENABLE, 
	"TELEFON" VARCHAR2(15) NOT NULL ENABLE, 
	"SALARIU" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "ANGAJAT_PK" PRIMARY KEY ("CNP") ENABLE
   )


CREATE TABLE  "CLIENT" 
   (	"ID_CLIENT" NUMBER(5,0) NOT NULL ENABLE, 
	"NUME_CLIENT" VARCHAR2(40) NOT NULL ENABLE, 
	"ADRESA" VARCHAR2(50) NOT NULL ENABLE, 
	"TELEFON" VARCHAR2(15) NOT NULL ENABLE, 
	 CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID_CLIENT") ENABLE
   )


CREATE TABLE  "CONTRACT" 
   (	"ID_CONTRACT" NUMBER(8,0) NOT NULL ENABLE, 
	"DATA_INCEPERE" DATE NOT NULL ENABLE, 
	"DATA_SFARSIT" DATE NOT NULL ENABLE, 
	"ID_PARTENER" NUMBER(8,0) NOT NULL ENABLE, 
	"ID_FIRMA" NUMBER(8,0) NOT NULL ENABLE, 
	 CONSTRAINT "CONTRACT_PK" PRIMARY KEY ("ID_CONTRACT") ENABLE
   )


CREATE TABLE  "FURNIZOR" 
   (	"COD_FURNIZOR" NUMBER(8,0) NOT NULL ENABLE, 
	"NUME" VARCHAR2(50) NOT NULL ENABLE, 
	"ADRESA" VARCHAR2(80) NOT NULL ENABLE, 
	"TELEFON" VARCHAR2(15) NOT NULL ENABLE, 
	"SITE" VARCHAR2(30), 
	 CONSTRAINT "FURNIZOR_PK" PRIMARY KEY ("COD_FURNIZOR") ENABLE
   )


CREATE TABLE  "FACTURA" 
   (	"ID_FACTURA" NUMBER(5,0) NOT NULL ENABLE, 
	"ID_ANGAJAT" NUMBER(13,0) NOT NULL ENABLE, 
	"ID_CLIENT" NUMBER(5,0) NOT NULL ENABLE, 
	"VALOARE" NUMBER(6,0) NOT NULL ENABLE, 
	"DATA" DATE NOT NULL ENABLE, 
	"DESCRIERE" VARCHAR2(100), 
	 CONSTRAINT "FACTURA_PK" PRIMARY KEY ("ID_FACTURA") ENABLE
   )


CREATE TABLE  "SHAORMERIE" 
   (	"COD_FIRMA" NUMBER(8,0) NOT NULL ENABLE, 
	"NUME" VARCHAR2(30) NOT NULL ENABLE, 
	"ADRESA" VARCHAR2(100) NOT NULL ENABLE, 
	"TELEFON" VARCHAR2(15) NOT NULL ENABLE, 
        "FAX" VARCHAR2(15) , 
	"SITE" VARCHAR2(25) , 
        "DETALII" VARCHAR2(200) , 
	 CONSTRAINT "FIRMA_PK" PRIMARY KEY ("COD_FIRMA") ENABLE
   )


CREATE TABLE  "LISTA" 
   (	"ID_LISTA" NUMBER(5,0) NOT NULL ENABLE, 
	"ID_PRODUS" NUMBER(5,0) NOT NULL ENABLE, 
	"ID_FACTURA" NUMBER(5,0) NOT NULL ENABLE, 
	"DESCRIERE" VARCHAR2(50), 
	 CONSTRAINT "LISTA_PK" PRIMARY KEY ("ID_LISTA") ENABLE
   )


CREATE TABLE  "PRODUS" 
   (	"ID_PRODUS" NUMBER(5,0) NOT NULL ENABLE, 
	"DENUMIRE" VARCHAR2(50) NOT NULL ENABLE, 
	"PRET" NUMBER(5,0) NOT NULL ENABLE, 
	"DESCRIERE" VARCHAR2(100), 
	 CONSTRAINT "PRODUS_PK" PRIMARY KEY ("ID_PRODUS") ENABLE
   )


alter table "CONTRACT" add constraint
"CONTRACT_CON1" foreign key ("ID_FIRMA") references "SHAORMERIE" ("COD_FIRMA")

alter table "CONTRACT" add constraint
"CONTRACT_CON2" foreign key ("ID_PARTENER") references "FURNIZOR" ("COD_FURNIZOR")

alter table "FACTURA" add constraint
"FACTURA_CON1" foreign key ("ID_ANGAJAT") references "ANGAJAT" ("CNP")

alter table "FACTURA" add constraint
"FACTURA_CON3" foreign key ("ID_CLIENT") references "CLIENT" ("ID_CLIENT")

alter table "LISTA" add constraint
"LISTA_CON1" foreign key ("ID_PRODUS") references "PRODUS" ("ID_PRODUS")

alter table "LISTA" add constraint
"LISTA_CON2" foreign key ("ID_FACTURA") references "FACTURA" ("ID_FACTURA")

